// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZI8FDqGA7SphwnWnh2EUAbCQ2YY8LPUs',
    appId: '1:129062883500:android:ff6dc0df21182ceac10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    storageBucket: 'enbla-app.firebasestorage.app',
  );

  // Web configuration - derived from existing Android config for local/dev use.
  // It's recommended to run `flutterfire configure` to generate proper web settings.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZI8FDqGA7SphwnWnh2EUAbCQ2YY8LPUs',
    appId: '1:129062883500:web:ff6dc0df21182ceac10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    storageBucket: 'enbla-app.firebasestorage.app',
  );
}