// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLIQ9uvijZTGy3MqrTUKutbTwZlZdaJs',
    appId: '1:129062883500:web:2d7c8b31d8c6062ac10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    authDomain: 'enbla-app.firebaseapp.com',
    storageBucket: 'enbla-app.firebasestorage.app',
    measurementId: 'G-GH9LGGXE7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZI8FDqGA7SphwnWnh2EUAbCQ2YY8LPUs',
    appId: '1:129062883500:android:ff6dc0df21182ceac10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    storageBucket: 'enbla-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQef0czbbtEyvHhrRngf_4nMMQJw-ggA',
    appId: '1:129062883500:ios:9a72ac0a87745448c10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    storageBucket: 'enbla-app.firebasestorage.app',
    iosBundleId: 'com.example.enblaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQef0czbbtEyvHhrRngf_4nMMQJw-ggA',
    appId: '1:129062883500:ios:9a72ac0a87745448c10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    storageBucket: 'enbla-app.firebasestorage.app',
    iosBundleId: 'com.example.enblaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYLIQ9uvijZTGy3MqrTUKutbTwZlZdaJs',
    appId: '1:129062883500:web:118a7b71180db448c10f09',
    messagingSenderId: '129062883500',
    projectId: 'enbla-app',
    authDomain: 'enbla-app.firebaseapp.com',
    storageBucket: 'enbla-app.firebasestorage.app',
    measurementId: 'G-YWDTFVR2SV',
  );
}
